# Generated by Django 3.2 on 2021-05-03 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='advisor_name',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='url',
            new_name='photo_url',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
