# Generated by Django 3.2 on 2021-05-05 11:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_auto_20210503_0642'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Advisor',
        ),
    ]
